version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      - . ~/.nvm/nvm.sh
      - source ~/.bashrc
      - nvm install --lts
      - node -e "console.log('Running Node.js ' + process.version)"
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-1 <REGION> s3 sync ./dist/ s3:/// --acl=public-read --delete
