version: 0.2

# phases:
#   install:
#     commands:
#      - printenv
#       - rm -rf node_modules
#       - npm install

#   build:
#     commands:
#       - npm run build -prod
#   post_build:
#     commands:
#       - aws --region us-east-1 <REGION> s3 sync ./dist/ s3://bucketforpipelinefresh/ --acl=public-read --delete

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:    
    commands:
      - echo prebuild phase

  build:
    commands:
      - echo build phase
      - node --version 
      - npm install
  post_build:
    commands:
      - ls -al
    - aws --region us-east-1 s3 sync ./dist/ s3://bucketforpipelinefresh/ --acl=public-read --delete
    
      # - aws --region us-east-1 s3 sync ./dist/ s3://bucketforpipelinefresh/ --acl=public-read --delete
