version: 0.2

phases:
  install:
    runtime-versions:
     nodejs: 20
  pre_build:    
    commands:
      - echo prebuild phase

  build:
    commands:
      - echo build phase
      - npm install --legacy-peer-deps
  post_build:
    commands:
    - pwd  # Print the current working directory
    - ls   # List the contents of the current directory
  #   artifacts:
  # files:
  #   - '**/*'
  # base-directory: 'dist'
    # - ls ./desktop/project/Let_the_Free_Times_Roll_BT  # List the contents of the specified directory
    - aws --region us-east-1 s3 sync . s3://bucketforpipelinefresh/  --delete
    # - aws s3 sync . s3://bucketforpipelinefresh/ --delete
      # - aws --region us-east-1 s3 sync /c/Users/Kwesi Baah Turkson/desktop/project/Let_the_Free_Times_Roll_BT s3://bucketforpipelinefresh/ --acl=public-read --delete

# phases:
#   install:
#     commands:
#      - printenv
#       - rm -rf node_modules
#       - npm install

#   build:
#     commands:
#       - npm run build -prod
#   post_build:
#     commands:
#       - aws --region us-east-1 <REGION> s3 sync /c/Users/Kwesi Baah Turkson/desktop/project/Let_the_Free_Times_Roll_BT s3://bucketforpipelinefresh/ --acl=public-read --delete

# phases:
#   install:
#     runtime-versions:
#       nodejs: 14.15
#   pre_build:    
#     commands:
#       - echo prebuild phase

#   build:
#     commands:
#       - echo build phase
#       - node --version 
#       - npm install
#   post_build:
#     commands:
#     - ls -al
#     - aws --region us-east-1 s3 sync ./dist/ s3://bucketforpipelinefresh/ --acl=public-read --delete
    
      # - aws --region us-east-1 s3 sync ./dist/ s3://bucketforpipelinefresh/ --acl=public-read --delete
