version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-1<REGION> s3 sync ./dist/ s3://bucketlabforpipe/ --acl=public-read --delete
