version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - sudo apt update
      - sudo apt install nodejs -y
      - node -v
      - npm install --force

  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-1 <REGION> s3 sync ./dist/ s3:/// --acl=public-read --delete
